package desafio

fun main() {
    var escola =  DigitalHouseManager()
    println("---> Registro de dois professores titulares")
    escola.registrarProfessorTitular("prof t1", "", 1,"esp1")
    escola.registrarProfessorTitular("prof t2", "", 2,"esp2")
    println("")
    println("---> Registro de dois professores adjuntos")
    escola.registrarProfessorAdjunto("prof a1", "", 3,0)
    escola.registrarProfessorAdjunto("prof a2", "", 4,0)
    println("")
    println("---> Registro de dois cursos")
    escola.registrarCurso("Full Stack",20001,3)
    escola.registrarCurso("Android",20002,2)
    println("")
    println("---> Alocagem de um professor titular e um adjunto para cada curso")
    escola.alocarProfessores(20001, 1, 3)
    escola.alocarProfessores(20002, 2, 4)
    println("")
    println("---> Registro inicial de dois alunos")
    escola.registrarAluno("aluno 1", "", 1)
    escola.registrarAluno("aluno 2", "", 2)
    println("")
    println("---> Matricula dos dois alunos no curso de Full Stack.")
    escola.matricularAluno(1, 20001)
    escola.matricularAluno(2, 20001)
    println("")
    println("---> Registro inicial de três alunos.")
    escola.registrarAluno("aluno 3", "", 3)
    escola.registrarAluno("aluno 4", "", 4)
    escola.registrarAluno("aluno 5", "", 5)
    println("")
    println("---> Matricula dos dois alunos no curso de Android.")
    escola.matricularAluno(3, 20002)
    escola.matricularAluno(4, 20002)
    escola.matricularAluno(5, 20002)
    println("")
    println("---> Exibe curso que aluno está matriculado.")
    escola.cursoMatriculado(1)
    escola.cursoMatriculado(2)
    escola.cursoMatriculado(3)
    escola.cursoMatriculado(4)
    escola.cursoMatriculado(5)
    escola.cursoMatriculado(6)
    println("")
    println("---> Exibi todas as informações")
    escola.exibeDados()
}